//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class MandatorRole : WoozleObject
    {
        public MandatorRole()
        {
            this.UserMandatorRoles = new ObservableCollection<UserMandatorRole>();
            this.FunctionPermissions = new ObservableCollection<FunctionPermission>();
        }
    
        private int mandid;
        private int roleid;
    
        public int MandId 
    	{ 
    		get { return this.mandid;} 
    		set { 
    			if(this.mandid != value)
    			{
    				this.mandid = value;
    			}
    		}
    	}
        public int RoleId 
    	{ 
    		get { return this.roleid;} 
    		set { 
    			if(this.roleid != value)
    			{
    				this.roleid = value;
    			}
    		}
    	}
    
    
    public virtual Mandator Mandator { get; set; }
    
    
    public virtual Role Role { get; set; }
    
    
    private ObservableCollection<UserMandatorRole> usermandatorroles;
    
    public virtual ObservableCollection<UserMandatorRole> UserMandatorRoles 
    { 
    	get { return usermandatorroles; } 
    	set
    	{
    		usermandatorroles = value;
    	}
    }
    
    
    private ObservableCollection<FunctionPermission> functionpermissions;
    
    public virtual ObservableCollection<FunctionPermission> FunctionPermissions 
    { 
    	get { return functionpermissions; } 
    	set
    	{
    		functionpermissions = value;
    	}
    }
    
    
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
