//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class NumberRange : WoozleObject, IMandatorCapable, IManagedConcurrency
    {
        private int from;
        private Nullable<int> till;
        private Nullable<int> current;
        private byte[] changecounter;
        private string name;
    
        public int From 
    	{ 
    		get { return this.from;} 
    		set { 
    			if(this.from != value)
    			{
    				this.from = value;
    			}
    		}
    	}
        public Nullable<int> Till 
    	{ 
    		get { return this.till;} 
    		set { 
    			if(this.till != value)
    			{
    				this.till = value;
    			}
    		}
    	}
        public Nullable<int> Current 
    	{ 
    		get { return this.current;} 
    		set { 
    			if(this.current != value)
    			{
    				this.current = value;
    			}
    		}
    	}
        public byte[] ChangeCounter 
    	{ 
    		get { return this.changecounter;} 
    		set { 
    			if(this.changecounter != value)
    			{
    				this.changecounter = value;
    			}
    		}
    	}
        public string Name 
    	{ 
    		get { return this.name;} 
    		set { 
    			if(this.name != value)
    			{
    				this.name = value;
    			}
    		}
    	}
    
    
    public virtual Mandator Mandator { get; set; }
    
    
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
