//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class Status : WoozleObject
    {
        public Status()
        {
            this.People = new ObservableCollection<Person>();
        }
    
        private string value;
        private int statusfieldid;
        private int translationid;
    
        public string Value 
    	{ 
    		get { return this.value;} 
    		set { 
    			if(this.value != value)
    			{
    				this.value = value;
    			}
    		}
    	}
        public int StatusFieldId 
    	{ 
    		get { return this.statusfieldid;} 
    		set { 
    			if(this.statusfieldid != value)
    			{
    				this.statusfieldid = value;
    			}
    		}
    	}
        public int TranslationId 
    	{ 
    		get { return this.translationid;} 
    		set { 
    			if(this.translationid != value)
    			{
    				this.translationid = value;
    			}
    		}
    	}
    	
    	/// <summary>
        /// To use the translated value directly it needs to be filled explicit
        /// </summary>
        public string TranslatedValue 	{ get; set; }
    
    
    
    public virtual StatusField StatusField { get; set; }
    
    
    public virtual Translation Translation { get; set; }
    
    
    private ObservableCollection<Person> people;
    
    public virtual ObservableCollection<Person> People 
    { 
    	get { return people; } 
    	set
    	{
    		people = value;
    	}
    }
    
    
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
