//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class Translation : WoozleObject
    {
        public Translation()
        {
            this.Countries = new ObservableCollection<Country>();
            this.Functions = new ObservableCollection<Function>();
            this.Modules = new ObservableCollection<Module>();
            this.Status = new ObservableCollection<Status>();
            this.TranslationItems = new ObservableCollection<TranslationItem>();
        }
    
        private string defaultdescription;
    
        public string DefaultDescription 
    	{ 
    		get { return this.defaultdescription;} 
    		set { 
    			if(this.defaultdescription != value)
    			{
    				this.defaultdescription = value;
    			}
    		}
    	}
    
    
    private ObservableCollection<Country> countries;
    
    public virtual ObservableCollection<Country> Countries 
    { 
    	get { return countries; } 
    	set
    	{
    		countries = value;
    	}
    }
    
    
    private ObservableCollection<Function> functions;
    
    public virtual ObservableCollection<Function> Functions 
    { 
    	get { return functions; } 
    	set
    	{
    		functions = value;
    	}
    }
    
    
    private ObservableCollection<Module> modules;
    
    public virtual ObservableCollection<Module> Modules 
    { 
    	get { return modules; } 
    	set
    	{
    		modules = value;
    	}
    }
    
    
    private ObservableCollection<Status> status;
    
    public virtual ObservableCollection<Status> Status 
    { 
    	get { return status; } 
    	set
    	{
    		status = value;
    	}
    }
    
    
    private ObservableCollection<TranslationItem> translationitems;
    
    public virtual ObservableCollection<TranslationItem> TranslationItems 
    { 
    	get { return translationitems; } 
    	set
    	{
    		translationitems = value;
    	}
    }
    
    
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
