//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System;
using System.Linq;
using Woozle.Model;
using Woozle.Model.SessionHandling;

namespace Woozle.Persistence.Ef.Repository
{
    public partial class FunctionPermissionRepository  : AbstractRepository<FunctionPermission>
    {
    
    	public FunctionPermissionRepository(IEfUnitOfWork Context) : base(Context)
    	{
    	}
    
    
    	 public override FunctionPermission Synchronize(FunctionPermission entity, Session session) 
    	 { 
    		try
    		{
    			var stopwatch = new Stopwatch();
    			var attachedObj = Context.SynchronizeObject(entity, session);
    			
    			attachedObj.Function = Context.SynchronizeObject(entity.Function, session); 
    
    			attachedObj.Permission = Context.SynchronizeObject(entity.Permission, session); 
    
    			
    			//Navigation Property 'MandatorRoles'
    			stopwatch.Start();
    			foreach(var n in entity.MandatorRoles.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.MandatorRoles.Contains(n)) attachedObj.MandatorRoles.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = session.SessionObject.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.MandatorRoles.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, session); 
    			} 
    			stopwatch.Stop();
    			this.Logger.Info(string.Format("Synchronize state of '{0}', took {1} ms", "MandatorRoles", stopwatch.ElapsedMilliseconds));
    			return attachedObj; 
    		}
    	catch (Exception e)
    	{
    		this.Logger.Error(e.Message); 
    		throw new PersistenceException(PersistenceOperation.SYNCHRONIZE, e); 
    	} 
      } 
    	 public override void Delete(FunctionPermission entity, Session session) 
    	 { 
    		try
    		{
    			var stopwatch = new Stopwatch();
    			entity.PersistanceState = PState.Unchanged;
    			var attachedObj = Context.SynchronizeObject(entity, session);
    			
    			Context.SynchronizeObject(attachedObj.Function, session); 
    
    			Context.SynchronizeObject(attachedObj.Permission, session); 
    
    			
    
    			//Navigation Property 'MandatorRoles'
    			stopwatch.Start();
    			Context.LoadCollection<FunctionPermission>(attachedObj.Id, "MandatorRoles");
    			foreach (var n in attachedObj.MandatorRoles.ToList())
    			{
    				n.PersistanceState = PState.Deleted;
    			    Context.SynchronizeObject(n, session);
    			} 
    			stopwatch.Stop();
    			this.Logger.Info(string.Format("Synchronize state of '{0}', took {1} ms", "MandatorRoles", stopwatch.ElapsedMilliseconds));
    			attachedObj.PersistanceState = PState.Deleted;
    			attachedObj = Context.SynchronizeObject(attachedObj, session);
    			stopwatch.Start();
    			Context.Commit();
    			stopwatch.Stop();
    			this.Logger.Info(string.Format("Commit '{0}' Delete, took {1} ms", "FunctionPermission", stopwatch.ElapsedMilliseconds));
    		}
    	catch (Exception e)
    	{
    		this.Logger.Error(e.Message); 
    		throw new PersistenceException(PersistenceOperation.DELETE, e);  
    	} 
      } 
    
    }
    
}
