//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System;
using System.Linq;
using System.Collections.Generic;
using Woozle.Model;
using Woozle.Model.SessionHandling;

namespace Woozle.Persistence.Ef.Repository
{
    public partial class MandatorRepository  : AbstractRepository<Mandator>
    {
    
    	public MandatorRepository(IEfUnitOfWork Context) : base(Context)
    	{
    	}
    
    
    	 public override Mandator Synchronize(Mandator entity, SessionData sessionData) 
    	 { 
    		try
    		{
    			var stopwatch = new Stopwatch();
    			var attachedObj = Context.SynchronizeObject(entity, sessionData);
    			
    			attachedObj.City = Context.SynchronizeObject(entity.City, sessionData); 
    
    			attachedObj.MandatorGroup = Context.SynchronizeObject(entity.MandatorGroup, sessionData); 
    
    			
    			//Navigation Property 'Modules'
    			stopwatch.Start();
    			foreach(var n in entity.Modules.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.Modules.Contains(n)) attachedObj.Modules.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.Modules.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "Modules", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'Locations'
    			stopwatch.Start();
    			foreach(var n in entity.Locations.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.Locations.Contains(n)) attachedObj.Locations.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.Locations.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "Locations", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'MandatorRoles'
    			stopwatch.Start();
    			foreach(var n in entity.MandatorRoles.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.MandatorRoles.Contains(n)) attachedObj.MandatorRoles.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.MandatorRoles.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "MandatorRoles", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'People'
    			stopwatch.Start();
    			foreach(var n in entity.People.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.People.Contains(n)) attachedObj.People.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.People.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "People", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'Settings'
    			stopwatch.Start();
    			foreach(var n in entity.Settings.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.Settings.Contains(n)) attachedObj.Settings.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.Settings.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "Settings", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'ExternalSystems'
    			stopwatch.Start();
    			foreach(var n in entity.ExternalSystems.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.ExternalSystems.Contains(n)) attachedObj.ExternalSystems.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.ExternalSystems.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "ExternalSystems", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'NumberRanges'
    			stopwatch.Start();
    			foreach(var n in entity.NumberRanges.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.NumberRanges.Contains(n)) attachedObj.NumberRanges.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.NumberRanges.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "NumberRanges", stopwatch.ElapsedMilliseconds));
    			return attachedObj; 
    		}
    		catch (Exception e)
    		{
    			Trace.TraceError(e.Message); 
    			throw new PersistenceException(PersistenceOperation.SYNCHRONIZE, e); 
    		} 
         } 
    
    }
    
}
