//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using System;
using System.Linq;
using System.Collections.Generic;
using Woozle.Model;
using Woozle.Model.SessionHandling;

namespace Woozle.Persistence.Ef.Repository
{
    public partial class ModuleRepository  : AbstractRepository<Module>
    {
    
    	public ModuleRepository(IEfUnitOfWork Context) : base(Context)
    	{
    	}
    
    
    	 public override Module Synchronize(Module entity, SessionData sessionData) 
    	 { 
    		try
    		{
    			var stopwatch = new Stopwatch();
    			var attachedObj = Context.SynchronizeObject(entity, sessionData);
    			
    			attachedObj.ModuleGroup = Context.SynchronizeObject(entity.ModuleGroup, sessionData); 
    
    			attachedObj.Translation = Context.SynchronizeObject(entity.Translation, sessionData); 
    
    			
    			//Navigation Property 'Functions'
    			stopwatch.Start();
    			foreach(var n in entity.Functions.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.Functions.Contains(n)) attachedObj.Functions.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.Functions.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "Functions", stopwatch.ElapsedMilliseconds));
    			//Navigation Property 'Mandators'
    			stopwatch.Start();
    			foreach(var n in entity.Mandators.Where(n => n.PersistanceState == PState.Added))
    			{ 
    				if (!attachedObj.Mandators.Contains(n)) attachedObj.Mandators.Add(n);
    				if (n is IMandatorCapable)
    				{
    					n.MandatorId = sessionData.Mandator.Id;
    				}
    			} 
    			foreach(var n in entity.Mandators.Where(n => n.PersistanceState == PState.Modified || n.PersistanceState == PState.Deleted))
    			{ 
    					Context.SynchronizeObject(n, sessionData); 
    			} 
    			stopwatch.Stop();
    			Trace.TraceInformation(string.Format("Synchronize state of '{0}', took {1} ms", "Mandators", stopwatch.ElapsedMilliseconds));
    			return attachedObj; 
    		}
    		catch (Exception e)
    		{
    			Trace.TraceError(e.Message); 
    			throw new PersistenceException(PersistenceOperation.SYNCHRONIZE, e); 
    		} 
         } 
    
    }
    
}
