//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(Woozle.Persistence.Ef.EfWoozleEntity),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets54acd979a40e9b913a4f0b1e836edbe35eb1f867e2b4c97a371d6ed24ace7df1))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySets54acd979a40e9b913a4f0b1e836edbe35eb1f867e2b4c97a371d6ed24ace7df1 : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "54acd979a40e9b913a4f0b1e836edbe35eb1f867e2b4c97a371d6ed24ace7df1"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "WoozleModelStoreContainer.City")
            {
                return GetView0();
            }

            if (extentName == "WoozleModelStoreContainer.Country")
            {
                return GetView1();
            }

            if (extentName == "WoozleModelStoreContainer.Function")
            {
                return GetView2();
            }

            if (extentName == "WoozleModelStoreContainer.FunctionPermission")
            {
                return GetView3();
            }

            if (extentName == "WoozleModelStoreContainer.Language")
            {
                return GetView4();
            }

            if (extentName == "WoozleModelStoreContainer.Mandator")
            {
                return GetView5();
            }

            if (extentName == "WoozleModelStoreContainer.Module")
            {
                return GetView6();
            }

            if (extentName == "WoozleModelStoreContainer.ModuleGroup")
            {
                return GetView7();
            }

            if (extentName == "WoozleModelStoreContainer.Permission")
            {
                return GetView8();
            }

            if (extentName == "WoozleModelStoreContainer.Role")
            {
                return GetView9();
            }

            if (extentName == "WoozleModelStoreContainer.Status")
            {
                return GetView10();
            }

            if (extentName == "WoozleModelStoreContainer.StatusField")
            {
                return GetView11();
            }

            if (extentName == "WoozleModelStoreContainer.Translation")
            {
                return GetView12();
            }

            if (extentName == "WoozleModelStoreContainer.TranslationItem")
            {
                return GetView13();
            }

            if (extentName == "WoozleModelStoreContainer.User")
            {
                return GetView14();
            }

            if (extentName == "WoozleModelStoreContainer.Location")
            {
                return GetView15();
            }

            if (extentName == "WoozleModelStoreContainer.MandatorRole")
            {
                return GetView16();
            }

            if (extentName == "WoozleModelStoreContainer.UserMandatorRole")
            {
                return GetView17();
            }

            if (extentName == "WoozleModelStoreContainer.Person")
            {
                return GetView18();
            }

            if (extentName == "WoozleModelStoreContainer.Settings")
            {
                return GetView19();
            }

            if (extentName == "WoozleModelStoreContainer.MandatorGroup")
            {
                return GetView20();
            }

            if (extentName == "WoozleModelStoreContainer.ExternalSystem")
            {
                return GetView21();
            }

            if (extentName == "WoozleModelStoreContainer.ExternalSystemType")
            {
                return GetView22();
            }

            if (extentName == "WoozleModelStoreContainer.MandatorModules")
            {
                return GetView23();
            }

            if (extentName == "WoozleModelStoreContainer.MandatorRoleFunctionPermission")
            {
                return GetView24();
            }

            if (extentName == "EfWoozleEntity.Cities")
            {
                return GetView25();
            }

            if (extentName == "EfWoozleEntity.Countries")
            {
                return GetView26();
            }

            if (extentName == "EfWoozleEntity.Functions")
            {
                return GetView27();
            }

            if (extentName == "EfWoozleEntity.FunctionPermissions")
            {
                return GetView28();
            }

            if (extentName == "EfWoozleEntity.Languages")
            {
                return GetView29();
            }

            if (extentName == "EfWoozleEntity.Mandators")
            {
                return GetView30();
            }

            if (extentName == "EfWoozleEntity.Modules")
            {
                return GetView31();
            }

            if (extentName == "EfWoozleEntity.ModuleGroups")
            {
                return GetView32();
            }

            if (extentName == "EfWoozleEntity.Permissions")
            {
                return GetView33();
            }

            if (extentName == "EfWoozleEntity.Roles")
            {
                return GetView34();
            }

            if (extentName == "EfWoozleEntity.Status")
            {
                return GetView35();
            }

            if (extentName == "EfWoozleEntity.StatusFields")
            {
                return GetView36();
            }

            if (extentName == "EfWoozleEntity.Translations")
            {
                return GetView37();
            }

            if (extentName == "EfWoozleEntity.TranslationItems")
            {
                return GetView38();
            }

            if (extentName == "EfWoozleEntity.Users")
            {
                return GetView39();
            }

            if (extentName == "EfWoozleEntity.Locations")
            {
                return GetView40();
            }

            if (extentName == "EfWoozleEntity.MandatorRoles")
            {
                return GetView41();
            }

            if (extentName == "EfWoozleEntity.UserMandatorRoles")
            {
                return GetView42();
            }

            if (extentName == "EfWoozleEntity.People")
            {
                return GetView43();
            }

            if (extentName == "EfWoozleEntity.Settings")
            {
                return GetView44();
            }

            if (extentName == "EfWoozleEntity.MandatorGroups")
            {
                return GetView45();
            }

            if (extentName == "EfWoozleEntity.ExternalSystems")
            {
                return GetView46();
            }

            if (extentName == "EfWoozleEntity.ExternalSystemTypes")
            {
                return GetView47();
            }

            if (extentName == "EfWoozleEntity.MandatorModules")
            {
                return GetView48();
            }

            if (extentName == "EfWoozleEntity.MandatorRoleFunctionPermission")
            {
                return GetView49();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.City.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing City
        [WoozleModel.Store.City](T1.City_Id, T1.City_ZipCode, T1.City_Name, T1.City_CountryId)
    FROM (
        SELECT 
            T.Id AS City_Id, 
            T.ZipCode AS City_ZipCode, 
            T.Name AS City_Name, 
            T.CountryId AS City_CountryId, 
            True AS _from0
        FROM EfWoozleEntity.Cities AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Country.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Country
        [WoozleModel.Store.Country](T1.Country_Id, T1.Country_TranslationId)
    FROM (
        SELECT 
            T.Id AS Country_Id, 
            T.TranslationId AS Country_TranslationId, 
            True AS _from0
        FROM EfWoozleEntity.Countries AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Function.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Function
        [WoozleModel.Store.Function](T1.Function_Id, T1.Function_Icon, T1.Function_Name, T1.Function_Description, T1.Function_ModuleId, T1.Function_LogicalId, T1.Function_TranslationId, T1.Function_Sequence)
    FROM (
        SELECT 
            T.Id AS Function_Id, 
            T.Icon AS Function_Icon, 
            T.Name AS Function_Name, 
            T.Description AS Function_Description, 
            T.ModuleId AS Function_ModuleId, 
            T.LogicalId AS Function_LogicalId, 
            T.TranslationId AS Function_TranslationId, 
            T.Sequence AS Function_Sequence, 
            True AS _from0
        FROM EfWoozleEntity.Functions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.FunctionPermission.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing FunctionPermission
        [WoozleModel.Store.FunctionPermission](T1.FunctionPermission_Id, T1.FunctionPermission_FunctionId, T1.FunctionPermission_PermissionId)
    FROM (
        SELECT 
            T.Id AS FunctionPermission_Id, 
            T.FunctionId AS FunctionPermission_FunctionId, 
            T.PermissionId AS FunctionPermission_PermissionId, 
            True AS _from0
        FROM EfWoozleEntity.FunctionPermissions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Language.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Language
        [WoozleModel.Store.Language](T1.Language_Id, T1.Language_Code, T1.Language_Name)
    FROM (
        SELECT 
            T.Id AS Language_Id, 
            T.Code AS Language_Code, 
            T.Name AS Language_Name, 
            True AS _from0
        FROM EfWoozleEntity.Languages AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Mandator.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Mandator
        [WoozleModel.Store.Mandator](T1.Mandator_Id, T1.Mandator_Name, T1.Mandator_Street, T1.Mandator_Phone, T1.Mandator_CityId, T1.Mandator_ChangeCounter, T1.Mandator_Email, T1.Mandator_Picture, T1.Mandator_MandatorGroupId)
    FROM (
        SELECT 
            T.Id AS Mandator_Id, 
            T.Name AS Mandator_Name, 
            T.Street AS Mandator_Street, 
            T.Phone AS Mandator_Phone, 
            T.CityId AS Mandator_CityId, 
            T.ChangeCounter AS Mandator_ChangeCounter, 
            T.Email AS Mandator_Email, 
            T.Picture AS Mandator_Picture, 
            T.MandatorGroupId AS Mandator_MandatorGroupId, 
            True AS _from0
        FROM EfWoozleEntity.Mandators AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Module.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Module
        [WoozleModel.Store.Module](T1.Module_Id, T1.Module_Icon, T1.Module_Name, T1.Module_Description, T1.Module_Version, T1.Module_ModuleGroupId, T1.Module_LogicalId, T1.Module_Sequence, T1.Module_TranslationId)
    FROM (
        SELECT 
            T.Id AS Module_Id, 
            T.Icon AS Module_Icon, 
            T.Name AS Module_Name, 
            T.Description AS Module_Description, 
            T.Version AS Module_Version, 
            T.ModuleGroupId AS Module_ModuleGroupId, 
            T.LogicalId AS Module_LogicalId, 
            T.Sequence AS Module_Sequence, 
            T.TranslationId AS Module_TranslationId, 
            True AS _from0
        FROM EfWoozleEntity.Modules AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.ModuleGroup.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ModuleGroup
        [WoozleModel.Store.ModuleGroup](T1.ModuleGroup_Id, T1.ModuleGroup_Icon, T1.ModuleGroup_Name, T1.ModuleGroup_Description)
    FROM (
        SELECT 
            T.Id AS ModuleGroup_Id, 
            T.Icon AS ModuleGroup_Icon, 
            T.Name AS ModuleGroup_Name, 
            T.Description AS ModuleGroup_Description, 
            True AS _from0
        FROM EfWoozleEntity.ModuleGroups AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Permission.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Permission
        [WoozleModel.Store.Permission](T1.Permission_Id, T1.Permission_Name, T1.Permission_Description, T1.Permission_LogicalId)
    FROM (
        SELECT 
            T.Id AS Permission_Id, 
            T.Name AS Permission_Name, 
            T.Description AS Permission_Description, 
            T.LogicalId AS Permission_LogicalId, 
            True AS _from0
        FROM EfWoozleEntity.Permissions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Role.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Role
        [WoozleModel.Store.Role](T1.Role_Id, T1.Role_Name, T1.Role_Description, T1.Role_LogicalId)
    FROM (
        SELECT 
            T.Id AS Role_Id, 
            T.Name AS Role_Name, 
            T.Description AS Role_Description, 
            T.LogicalId AS Role_LogicalId, 
            True AS _from0
        FROM EfWoozleEntity.Roles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Status.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Status
        [WoozleModel.Store.Status](T1.Status_Id, T1.Status_Value, T1.Status_StatusFieldId, T1.Status_TranslationId)
    FROM (
        SELECT 
            T.Id AS Status_Id, 
            T.[Value] AS Status_Value, 
            T.StatusFieldId AS Status_StatusFieldId, 
            T.TranslationId AS Status_TranslationId, 
            True AS _from0
        FROM EfWoozleEntity.Status AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.StatusField.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing StatusField
        [WoozleModel.Store.StatusField](T1.StatusField_Id, T1.StatusField_Name)
    FROM (
        SELECT 
            T.Id AS StatusField_Id, 
            T.Name AS StatusField_Name, 
            True AS _from0
        FROM EfWoozleEntity.StatusFields AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Translation.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Translation
        [WoozleModel.Store.Translation](T1.Translation_Id, T1.Translation_DefaultDescription)
    FROM (
        SELECT 
            T.Id AS Translation_Id, 
            T.DefaultDescription AS Translation_DefaultDescription, 
            True AS _from0
        FROM EfWoozleEntity.Translations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.TranslationItem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TranslationItem
        [WoozleModel.Store.TranslationItem](T1.TranslationItem_Id, T1.TranslationItem_TranslationId, T1.TranslationItem_LanguageId, T1.TranslationItem_Description)
    FROM (
        SELECT 
            T.Id AS TranslationItem_Id, 
            T.TranslationId AS TranslationItem_TranslationId, 
            T.LanguageId AS TranslationItem_LanguageId, 
            T.Description AS TranslationItem_Description, 
            True AS _from0
        FROM EfWoozleEntity.TranslationItems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.User.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing User
        [WoozleModel.Store.User](T1.User_Id, T1.User_Username, T1.User_Password, T1.User_FlagActive, T1.User_LastLogin, T1.User_LastPasswordChange, T1.User_LanguageId, T1.User_FlagActiveStatusId, T1.User_ChangeCounter, T1.User_FirstName, T1.User_LastName, T1.User_Email)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Username AS User_Username, 
            T.Password AS User_Password, 
            T.FlagActive AS User_FlagActive, 
            T.LastLogin AS User_LastLogin, 
            T.LastPasswordChange AS User_LastPasswordChange, 
            T.LanguageId AS User_LanguageId, 
            T.FlagActiveStatusId AS User_FlagActiveStatusId, 
            T.ChangeCounter AS User_ChangeCounter, 
            T.FirstName AS User_FirstName, 
            T.LastName AS User_LastName, 
            T.Email AS User_Email, 
            True AS _from0
        FROM EfWoozleEntity.Users AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Location.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Location
        [WoozleModel.Store.Location](T1.Location_Id, T1.Location_MandatorId, T1.Location_Name, T1.Location_Street, T1.Location_CityId)
    FROM (
        SELECT 
            T.Id AS Location_Id, 
            T.MandatorId AS Location_MandatorId, 
            T.Name AS Location_Name, 
            T.Street AS Location_Street, 
            T.CityId AS Location_CityId, 
            True AS _from0
        FROM EfWoozleEntity.Locations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.MandatorRole.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorRole
        [WoozleModel.Store.MandatorRole](T1.MandatorRole_Id, T1.MandatorRole_MandId, T1.MandatorRole_RoleId)
    FROM (
        SELECT 
            T.Id AS MandatorRole_Id, 
            T.MandId AS MandatorRole_MandId, 
            T.RoleId AS MandatorRole_RoleId, 
            True AS _from0
        FROM EfWoozleEntity.MandatorRoles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.UserMandatorRole.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMandatorRole
        [WoozleModel.Store.UserMandatorRole](T1.UserMandatorRole_Id, T1.UserMandatorRole_UserId, T1.UserMandatorRole_MandatorRoleId)
    FROM (
        SELECT 
            T.Id AS UserMandatorRole_Id, 
            T.UserId AS UserMandatorRole_UserId, 
            T.MandatorRoleId AS UserMandatorRole_MandatorRoleId, 
            True AS _from0
        FROM EfWoozleEntity.UserMandatorRoles AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Person.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Person
        [WoozleModel.Store.Person](T1.Person_Id, T1.Person_LastName, T1.Person_FirstName, T1.Person_EMail, T1.Person_Picture, T1.Person_MandatorId, T1.Person_Street, T1.Person_CityId, T1.Person_Phone, T1.Person_Mobile, T1.Person_Birthdate, T1.Person_EnterpriseName, T1.Person_SalutationStatusId, T1.Person_ChangeCounter)
    FROM (
        SELECT 
            T.Id AS Person_Id, 
            T.LastName AS Person_LastName, 
            T.FirstName AS Person_FirstName, 
            T.EMail AS Person_EMail, 
            T.Picture AS Person_Picture, 
            T.MandatorId AS Person_MandatorId, 
            T.Street AS Person_Street, 
            T.CityId AS Person_CityId, 
            T.Phone AS Person_Phone, 
            T.Mobile AS Person_Mobile, 
            T.Birthdate AS Person_Birthdate, 
            T.EnterpriseName AS Person_EnterpriseName, 
            T.SalutationStatusId AS Person_SalutationStatusId, 
            T.ChangeCounter AS Person_ChangeCounter, 
            True AS _from0
        FROM EfWoozleEntity.People AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.Settings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Settings
        [WoozleModel.Store.Settings](T1.Settings_Id, T1.Settings_MandatorId, T1.Settings_EventManagementPlanningEMail, T1.Settings_EventManagementPlanningMobile, T1.Settings_ChangeCounter)
    FROM (
        SELECT 
            T.Id AS Settings_Id, 
            T.MandatorId AS Settings_MandatorId, 
            T.EventManagementPlanningEMail AS Settings_EventManagementPlanningEMail, 
            T.EventManagementPlanningMobile AS Settings_EventManagementPlanningMobile, 
            T.ChangeCounter AS Settings_ChangeCounter, 
            True AS _from0
        FROM EfWoozleEntity.Settings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.MandatorGroup.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorGroup
        [WoozleModel.Store.MandatorGroup](T1.MandatorGroup_Id, T1.MandatorGroup_Name)
    FROM (
        SELECT 
            T.Id AS MandatorGroup_Id, 
            T.Name AS MandatorGroup_Name, 
            True AS _from0
        FROM EfWoozleEntity.MandatorGroups AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.ExternalSystem.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExternalSystem
        [WoozleModel.Store.ExternalSystem](T1.ExternalSystem_Id, T1.ExternalSystem_MandatorId, T1.ExternalSystem_ExternalSystemTypeId, T1.ExternalSystem_Name)
    FROM (
        SELECT 
            T.Id AS ExternalSystem_Id, 
            T.MandatorId AS ExternalSystem_MandatorId, 
            T.ExternalSystemTypeId AS ExternalSystem_ExternalSystemTypeId, 
            T.Name AS ExternalSystem_Name, 
            True AS _from0
        FROM EfWoozleEntity.ExternalSystems AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.ExternalSystemType.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExternalSystemType
        [WoozleModel.Store.ExternalSystemType](T1.ExternalSystemType_Id, T1.ExternalSystemType_Name)
    FROM (
        SELECT 
            T.Id AS ExternalSystemType_Id, 
            T.Name AS ExternalSystemType_Name, 
            True AS _from0
        FROM EfWoozleEntity.ExternalSystemTypes AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.MandatorModules.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorModules
        [WoozleModel.Store.MandatorModules](T1.MandatorModules_ModuleId, T1.MandatorModules_MandatorId)
    FROM (
        SELECT 
            Key(T.Module).Id AS MandatorModules_ModuleId, 
            Key(T.Mandator).Id AS MandatorModules_MandatorId, 
            True AS _from0
        FROM EfWoozleEntity.MandatorModules AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for WoozleModelStoreContainer.MandatorRoleFunctionPermission.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorRoleFunctionPermission
        [WoozleModel.Store.MandatorRoleFunctionPermission](T1.MandatorRoleFunctionPermission_MandatorRoleId, T1.MandatorRoleFunctionPermission_FunctionPermissionId)
    FROM (
        SELECT 
            Key(T.MandatorRole).Id AS MandatorRoleFunctionPermission_MandatorRoleId, 
            Key(T.FunctionPermission).Id AS MandatorRoleFunctionPermission_FunctionPermissionId, 
            True AS _from0
        FROM EfWoozleEntity.MandatorRoleFunctionPermission AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Cities.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Cities
        [WoozleModel.City](T1.City_Id, T1.City_ZipCode, T1.City_Name, T1.City_CountryId)
    FROM (
        SELECT 
            T.Id AS City_Id, 
            T.ZipCode AS City_ZipCode, 
            T.Name AS City_Name, 
            T.CountryId AS City_CountryId, 
            True AS _from0
        FROM WoozleModelStoreContainer.City AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Countries.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Countries
        [WoozleModel.Country](T1.Country_Id, T1.Country_TranslationId)
    FROM (
        SELECT 
            T.Id AS Country_Id, 
            T.TranslationId AS Country_TranslationId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Country AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Functions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Functions
        [WoozleModel.Function](T1.Function_Id, T1.Function_Icon, T1.Function_Name, T1.Function_Description, T1.Function_ModuleId, T1.Function_LogicalId, T1.Function_TranslationId, T1.Function_Sequence)
    FROM (
        SELECT 
            T.Id AS Function_Id, 
            T.Icon AS Function_Icon, 
            T.Name AS Function_Name, 
            T.Description AS Function_Description, 
            T.ModuleId AS Function_ModuleId, 
            T.LogicalId AS Function_LogicalId, 
            T.TranslationId AS Function_TranslationId, 
            T.Sequence AS Function_Sequence, 
            True AS _from0
        FROM WoozleModelStoreContainer.[Function] AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.FunctionPermissions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView28()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing FunctionPermissions
        [WoozleModel.FunctionPermission](T1.FunctionPermission_Id, T1.FunctionPermission_FunctionId, T1.FunctionPermission_PermissionId)
    FROM (
        SELECT 
            T.Id AS FunctionPermission_Id, 
            T.FunctionId AS FunctionPermission_FunctionId, 
            T.PermissionId AS FunctionPermission_PermissionId, 
            True AS _from0
        FROM WoozleModelStoreContainer.FunctionPermission AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Languages.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView29()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Languages
        [WoozleModel.Language](T1.Language_Id, T1.Language_Code, T1.Language_Name)
    FROM (
        SELECT 
            T.Id AS Language_Id, 
            T.Code AS Language_Code, 
            T.Name AS Language_Name, 
            True AS _from0
        FROM WoozleModelStoreContainer.Language AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Mandators.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView30()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Mandators
        [WoozleModel.Mandator](T1.Mandator_Id, T1.Mandator_Name, T1.Mandator_Street, T1.Mandator_Phone, T1.Mandator_CityId, T1.Mandator_ChangeCounter, T1.Mandator_Email, T1.Mandator_Picture, T1.Mandator_MandatorGroupId)
    FROM (
        SELECT 
            T.Id AS Mandator_Id, 
            T.Name AS Mandator_Name, 
            T.Street AS Mandator_Street, 
            T.Phone AS Mandator_Phone, 
            T.CityId AS Mandator_CityId, 
            T.ChangeCounter AS Mandator_ChangeCounter, 
            T.Email AS Mandator_Email, 
            T.Picture AS Mandator_Picture, 
            T.MandatorGroupId AS Mandator_MandatorGroupId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Mandator AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Modules.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView31()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Modules
        [WoozleModel.Module](T1.Module_Id, T1.Module_Icon, T1.Module_Name, T1.Module_Description, T1.Module_Version, T1.Module_ModuleGroupId, T1.Module_LogicalId, T1.Module_Sequence, T1.Module_TranslationId)
    FROM (
        SELECT 
            T.Id AS Module_Id, 
            T.Icon AS Module_Icon, 
            T.Name AS Module_Name, 
            T.Description AS Module_Description, 
            T.Version AS Module_Version, 
            T.ModuleGroupId AS Module_ModuleGroupId, 
            T.LogicalId AS Module_LogicalId, 
            T.Sequence AS Module_Sequence, 
            T.TranslationId AS Module_TranslationId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Module AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.ModuleGroups.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView32()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ModuleGroups
        [WoozleModel.ModuleGroup](T1.ModuleGroup_Id, T1.ModuleGroup_Icon, T1.ModuleGroup_Name, T1.ModuleGroup_Description)
    FROM (
        SELECT 
            T.Id AS ModuleGroup_Id, 
            T.Icon AS ModuleGroup_Icon, 
            T.Name AS ModuleGroup_Name, 
            T.Description AS ModuleGroup_Description, 
            True AS _from0
        FROM WoozleModelStoreContainer.ModuleGroup AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Permissions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView33()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Permissions
        [WoozleModel.Permission](T1.Permission_Id, T1.Permission_Name, T1.Permission_Description, T1.Permission_LogicalId)
    FROM (
        SELECT 
            T.Id AS Permission_Id, 
            T.Name AS Permission_Name, 
            T.Description AS Permission_Description, 
            T.LogicalId AS Permission_LogicalId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Permission AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Roles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView34()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Roles
        [WoozleModel.Role](T1.Role_Id, T1.Role_Name, T1.Role_Description, T1.Role_LogicalId)
    FROM (
        SELECT 
            T.Id AS Role_Id, 
            T.Name AS Role_Name, 
            T.Description AS Role_Description, 
            T.LogicalId AS Role_LogicalId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Role AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Status.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView35()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Status
        [WoozleModel.Status](T1.Status_Id, T1.Status_Value, T1.Status_StatusFieldId, T1.Status_TranslationId)
    FROM (
        SELECT 
            T.Id AS Status_Id, 
            T.[Value] AS Status_Value, 
            T.StatusFieldId AS Status_StatusFieldId, 
            T.TranslationId AS Status_TranslationId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Status AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.StatusFields.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView36()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing StatusFields
        [WoozleModel.StatusField](T1.StatusField_Id, T1.StatusField_Name)
    FROM (
        SELECT 
            T.Id AS StatusField_Id, 
            T.Name AS StatusField_Name, 
            True AS _from0
        FROM WoozleModelStoreContainer.StatusField AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Translations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView37()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Translations
        [WoozleModel.Translation](T1.Translation_Id, T1.Translation_DefaultDescription)
    FROM (
        SELECT 
            T.Id AS Translation_Id, 
            T.DefaultDescription AS Translation_DefaultDescription, 
            True AS _from0
        FROM WoozleModelStoreContainer.Translation AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.TranslationItems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView38()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TranslationItems
        [WoozleModel.TranslationItem](T1.TranslationItem_Id, T1.TranslationItem_TranslationId, T1.TranslationItem_LanguageId, T1.TranslationItem_Description)
    FROM (
        SELECT 
            T.Id AS TranslationItem_Id, 
            T.TranslationId AS TranslationItem_TranslationId, 
            T.LanguageId AS TranslationItem_LanguageId, 
            T.Description AS TranslationItem_Description, 
            True AS _from0
        FROM WoozleModelStoreContainer.TranslationItem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Users.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView39()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Users
        [WoozleModel.User](T1.User_Id, T1.User_Username, T1.User_Password, T1.User_FlagActive, T1.User_LastLogin, T1.User_LastPasswordChange, T1.User_LanguageId, T1.User_FlagActiveStatusId, T1.User_ChangeCounter, T1.User_FirstName, T1.User_LastName, T1.User_Email)
    FROM (
        SELECT 
            T.Id AS User_Id, 
            T.Username AS User_Username, 
            T.Password AS User_Password, 
            T.FlagActive AS User_FlagActive, 
            T.LastLogin AS User_LastLogin, 
            T.LastPasswordChange AS User_LastPasswordChange, 
            T.LanguageId AS User_LanguageId, 
            T.FlagActiveStatusId AS User_FlagActiveStatusId, 
            T.ChangeCounter AS User_ChangeCounter, 
            T.FirstName AS User_FirstName, 
            T.LastName AS User_LastName, 
            T.Email AS User_Email, 
            True AS _from0
        FROM WoozleModelStoreContainer.User AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Locations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView40()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Locations
        [WoozleModel.Location](T1.Location_Id, T1.Location_MandatorId, T1.Location_Name, T1.Location_Street, T1.Location_CityId)
    FROM (
        SELECT 
            T.Id AS Location_Id, 
            T.MandatorId AS Location_MandatorId, 
            T.Name AS Location_Name, 
            T.Street AS Location_Street, 
            T.CityId AS Location_CityId, 
            True AS _from0
        FROM WoozleModelStoreContainer.Location AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.MandatorRoles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView41()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorRoles
        [WoozleModel.MandatorRole](T1.MandatorRole_Id, T1.MandatorRole_MandId, T1.MandatorRole_RoleId)
    FROM (
        SELECT 
            T.Id AS MandatorRole_Id, 
            T.MandId AS MandatorRole_MandId, 
            T.RoleId AS MandatorRole_RoleId, 
            True AS _from0
        FROM WoozleModelStoreContainer.MandatorRole AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.UserMandatorRoles.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView42()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing UserMandatorRoles
        [WoozleModel.UserMandatorRole](T1.UserMandatorRole_Id, T1.UserMandatorRole_UserId, T1.UserMandatorRole_MandatorRoleId)
    FROM (
        SELECT 
            T.Id AS UserMandatorRole_Id, 
            T.UserId AS UserMandatorRole_UserId, 
            T.MandatorRoleId AS UserMandatorRole_MandatorRoleId, 
            True AS _from0
        FROM WoozleModelStoreContainer.UserMandatorRole AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.People.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView43()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing People
        [WoozleModel.Person](T1.Person_Id, T1.Person_LastName, T1.Person_FirstName, T1.Person_EMail, T1.Person_Picture, T1.Person_MandatorId, T1.Person_Street, T1.Person_CityId, T1.Person_Phone, T1.Person_Mobile, T1.Person_Birthdate, T1.Person_EnterpriseName, T1.Person_SalutationStatusId, T1.Person_ChangeCounter)
    FROM (
        SELECT 
            T.Id AS Person_Id, 
            T.LastName AS Person_LastName, 
            T.FirstName AS Person_FirstName, 
            T.EMail AS Person_EMail, 
            T.Picture AS Person_Picture, 
            T.MandatorId AS Person_MandatorId, 
            T.Street AS Person_Street, 
            T.CityId AS Person_CityId, 
            T.Phone AS Person_Phone, 
            T.Mobile AS Person_Mobile, 
            T.Birthdate AS Person_Birthdate, 
            T.EnterpriseName AS Person_EnterpriseName, 
            T.SalutationStatusId AS Person_SalutationStatusId, 
            T.ChangeCounter AS Person_ChangeCounter, 
            True AS _from0
        FROM WoozleModelStoreContainer.Person AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.Settings.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView44()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Settings
        [WoozleModel.Setting](T1.Setting_Id, T1.Setting_MandatorId, T1.Setting_EventManagementPlanningEMail, T1.Setting_EventManagementPlanningMobile, T1.Setting_ChangeCounter)
    FROM (
        SELECT 
            T.Id AS Setting_Id, 
            T.MandatorId AS Setting_MandatorId, 
            T.EventManagementPlanningEMail AS Setting_EventManagementPlanningEMail, 
            T.EventManagementPlanningMobile AS Setting_EventManagementPlanningMobile, 
            T.ChangeCounter AS Setting_ChangeCounter, 
            True AS _from0
        FROM WoozleModelStoreContainer.Settings AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.MandatorGroups.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView45()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorGroups
        [WoozleModel.MandatorGroup](T1.MandatorGroup_Id, T1.MandatorGroup_Name)
    FROM (
        SELECT 
            T.Id AS MandatorGroup_Id, 
            T.Name AS MandatorGroup_Name, 
            True AS _from0
        FROM WoozleModelStoreContainer.MandatorGroup AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.ExternalSystems.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView46()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExternalSystems
        [WoozleModel.ExternalSystem](T1.ExternalSystem_Id, T1.ExternalSystem_MandatorId, T1.ExternalSystem_ExternalSystemTypeId, T1.ExternalSystem_Name)
    FROM (
        SELECT 
            T.Id AS ExternalSystem_Id, 
            T.MandatorId AS ExternalSystem_MandatorId, 
            T.ExternalSystemTypeId AS ExternalSystem_ExternalSystemTypeId, 
            T.Name AS ExternalSystem_Name, 
            True AS _from0
        FROM WoozleModelStoreContainer.ExternalSystem AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.ExternalSystemTypes.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView47()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ExternalSystemTypes
        [WoozleModel.ExternalSystemType](T1.ExternalSystemType_Id, T1.ExternalSystemType_Name)
    FROM (
        SELECT 
            T.Id AS ExternalSystemType_Id, 
            T.Name AS ExternalSystemType_Name, 
            True AS _from0
        FROM WoozleModelStoreContainer.ExternalSystemType AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.MandatorModules.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView48()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorModules
        [WoozleModel.MandatorModules](T3.MandatorModules_Mandator, T3.MandatorModules_Module)
    FROM (
        SELECT -- Constructing Mandator
            CreateRef(EfWoozleEntity.Mandators, row(T2.MandatorModules_Mandator_Id), [WoozleModel.Mandator]) AS MandatorModules_Mandator, 
            T2.MandatorModules_Module
        FROM (
            SELECT -- Constructing Module
                T1.MandatorModules_Mandator_Id, 
                CreateRef(EfWoozleEntity.Modules, row(T1.MandatorModules_Module_Id), [WoozleModel.Module]) AS MandatorModules_Module
            FROM (
                SELECT 
                    T.MandatorId AS MandatorModules_Mandator_Id, 
                    T.ModuleId AS MandatorModules_Module_Id, 
                    True AS _from0
                FROM WoozleModelStoreContainer.MandatorModules AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for EfWoozleEntity.MandatorRoleFunctionPermission.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView49()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing MandatorRoleFunctionPermission
        [WoozleModel.MandatorRoleFunctionPermission](T3.MandatorRoleFunctionPermission_FunctionPermission, T3.MandatorRoleFunctionPermission_MandatorRole)
    FROM (
        SELECT -- Constructing FunctionPermission
            CreateRef(EfWoozleEntity.FunctionPermissions, row(T2.MandatorRoleFunctionPermission_FunctionPermission_Id), [WoozleModel.FunctionPermission]) AS MandatorRoleFunctionPermission_FunctionPermission, 
            T2.MandatorRoleFunctionPermission_MandatorRole
        FROM (
            SELECT -- Constructing MandatorRole
                T1.MandatorRoleFunctionPermission_FunctionPermission_Id, 
                CreateRef(EfWoozleEntity.MandatorRoles, row(T1.MandatorRoleFunctionPermission_MandatorRole_Id), [WoozleModel.MandatorRole]) AS MandatorRoleFunctionPermission_MandatorRole
            FROM (
                SELECT 
                    T.FunctionPermissionId AS MandatorRoleFunctionPermission_FunctionPermission_Id, 
                    T.MandatorRoleId AS MandatorRoleFunctionPermission_MandatorRole_Id, 
                    True AS _from0
                FROM WoozleModelStoreContainer.MandatorRoleFunctionPermission AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
    }
}
