//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Diagnostics;
using Woozle.Core.Persistence.Repository;
using Woozle.Core.Model;
using System;
using System.Linq;
using System.Collections.Generic;
using Woozle.Core.Model.SessionHandling;
using Woozle.Core.Persistence.Impl;
using Woozle.Model;

namespace Woozle.Persistence.Repository
{
}
