//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Woozle.Core.Services.Stack.ServiceModel.Authority;

namespace Woozle.Core.Services.Stack.ServiceModel.UserManagement
{
    [Serializable]
    public partial class UserMandatorRole : WoozleDto
    {
        public int UserId { get; set; }
        public int MandatorRoleId { get; set; }
    
        public MandatorRole MandatorRole { get; set; }
        public User User { get; set; }
    }
    
}
