//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Woozle.Services;
using Woozle.Services.Authority;
using Woozle.Services.UserManagement;

namespace Woozle.Service.UserManagement
{
    [Serializable]
    public partial class UserMandatorRoleDto : WoozleDto
    {
        public int UserId { get; set; }
        public int MandatorRoleId { get; set; }
    
        public MandatorRole MandatorRole { get; set; }
        public UserDto UserDto { get; set; }
    }
    
}
