//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Woozle.Model;

namespace Woozle.Services.Modules
{
    [Serializable]
    public partial class ModuleGroupDto : WoozleDto
    {
        public ModuleGroupDto()
        {
            this.Modules = new FixupCollection<ModuleDto>();
        }
    
        public byte[] Icon { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public FixupCollection<ModuleDto> Modules { get; set; }
    
    }
    
}
