//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;
using Woozle.Core.Model;

namespace Woozle.Model
{
    [Serializable]
    public partial class MandatorRole : WoozleObject
    {
        public MandatorRole()
        {
            this.UserMandatorRoles = new FixupCollection<UserMandatorRole>();
            this.FunctionPermissions = new FixupCollection<FunctionPermission>();
        }
    
        private int mandid;
        private int roleid;
    
        public int MandId 
    	{ 
    		get { return this.mandid;} 
    		set { 
    			if(this.mandid != value)
    			{
    				this.mandid = value;
    				OnPropertyChanged("MandId");
    			}
    		}
    	}
        public int RoleId 
    	{ 
    		get { return this.roleid;} 
    		set { 
    			if(this.roleid != value)
    			{
    				this.roleid = value;
    				OnPropertyChanged("RoleId");
    			}
    		}
    	}
    
    
    public virtual Mandator Mandator { get; set; }
    
    
    public virtual Role Role { get; set; }
    
    
    private FixupCollection<UserMandatorRole> usermandatorroles;
    
    public virtual FixupCollection<UserMandatorRole> UserMandatorRoles 
    { 
    	get { return usermandatorroles; } 
    	set
    	{
    		usermandatorroles = value;
    		if(value != null)
    		{
    			UserMandatorRoles.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    private FixupCollection<FunctionPermission> functionpermissions;
    
    public virtual FixupCollection<FunctionPermission> FunctionPermissions 
    { 
    	get { return functionpermissions; } 
    	set
    	{
    		functionpermissions = value;
    		if(value != null)
    		{
    			FunctionPermissions.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    public event PropertyChangedEventHandler LocalPropertyChanged;
    private event EventHandler AnyPropertyChanged;
    
    protected void OnPropertyChanged(String propertyName)
    {
    	if (this.LocalPropertyChanged != null)
        {
            this.LocalPropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }
    
    private void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
    {
    	OnPropertyChanged("Collection");
    }
    
    public void HandleLocalPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
    	this.PersistanceState = PState.Modified;
    	AnyPropertyChanged(sender, e);
    }
    
    public void HandleAnyPropertyChanged(object sender, EventArgs e)
    {
    	this.Dirty = true;
    }
    
    public override void ActivatePropertyChangedEvent(bool resetPersistenceState)
    {
    	ActivatePropertyChangedEvent(resetPersistenceState, HandleAnyPropertyChanged);
    }
    
    public void ActivatePropertyChangedEvent(bool resetPersistenceState, EventHandler anyPropertyChangedHandler)
    {
    	if (this.LocalPropertyChanged == null && this.AnyPropertyChanged == null)
    	{
    		if(resetPersistenceState) 
    		{
    			this.PersistanceState = PState.Unchanged;
    			this.Dirty = false;
    		}
    
    		this.LocalPropertyChanged += HandleLocalPropertyChanged;
            this.AnyPropertyChanged += anyPropertyChangedHandler;
    
    		if(Mandator != null)
    		{
    			Mandator.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    		}
    
    
    		if(Role != null)
    		{
    			Role.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    		}
    
    		if(UserMandatorRoles != null)
    		{
    			foreach(var n in UserMandatorRoles) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    		if(FunctionPermissions != null)
    		{
    			foreach(var n in FunctionPermissions) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    	}
    }
    
    public override void DeactivatePropertyChangedEvent()
    {
    	if(this.LocalPropertyChanged != null && this.AnyPropertyChanged != null) 
    	{
    		this.LocalPropertyChanged = null;
    		this.AnyPropertyChanged = null;
    		if(Mandator != null)
    		{
    			Mandator.DeactivatePropertyChangedEvent();
    		}
    		if(Role != null)
    		{
    			Role.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in UserMandatorRoles) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in FunctionPermissions) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    	}
    }
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
