//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class Translation : WoozleObject
    {
        public Translation()
        {
            this.Countries = new FixupCollection<Country>();
            this.Functions = new FixupCollection<Function>();
            this.Modules = new FixupCollection<Module>();
            this.Status = new FixupCollection<Status>();
            this.TranslationItems = new FixupCollection<TranslationItem>();
        }
    
        private string defaultdescription;
    
        public string DefaultDescription 
    	{ 
    		get { return this.defaultdescription;} 
    		set { 
    			if(this.defaultdescription != value)
    			{
    				this.defaultdescription = value;
    				OnPropertyChanged("DefaultDescription");
    			}
    		}
    	}
    
    
    private FixupCollection<Country> countries;
    
    public virtual FixupCollection<Country> Countries 
    { 
    	get { return countries; } 
    	set
    	{
    		countries = value;
    		if(value != null)
    		{
    			Countries.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    private FixupCollection<Function> functions;
    
    public virtual FixupCollection<Function> Functions 
    { 
    	get { return functions; } 
    	set
    	{
    		functions = value;
    		if(value != null)
    		{
    			Functions.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    private FixupCollection<Module> modules;
    
    public virtual FixupCollection<Module> Modules 
    { 
    	get { return modules; } 
    	set
    	{
    		modules = value;
    		if(value != null)
    		{
    			Modules.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    private FixupCollection<Status> status;
    
    public virtual FixupCollection<Status> Status 
    { 
    	get { return status; } 
    	set
    	{
    		status = value;
    		if(value != null)
    		{
    			Status.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    private FixupCollection<TranslationItem> translationitems;
    
    public virtual FixupCollection<TranslationItem> TranslationItems 
    { 
    	get { return translationitems; } 
    	set
    	{
    		translationitems = value;
    		if(value != null)
    		{
    			TranslationItems.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    public event PropertyChangedEventHandler LocalPropertyChanged;
    private event EventHandler AnyPropertyChanged;
    
    protected void OnPropertyChanged(String propertyName)
    {
    	if (this.LocalPropertyChanged != null)
        {
            this.LocalPropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }
    
    private void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
    {
    	OnPropertyChanged("Collection");
    }
    
    public void HandleLocalPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
    	this.PersistanceState = PState.Modified;
    	AnyPropertyChanged(sender, e);
    }
    
    public void HandleAnyPropertyChanged(object sender, EventArgs e)
    {
    	this.Dirty = true;
    }
    
    public override void ActivatePropertyChangedEvent(bool resetPersistenceState)
    {
    	ActivatePropertyChangedEvent(resetPersistenceState, HandleAnyPropertyChanged);
    }
    
    public void ActivatePropertyChangedEvent(bool resetPersistenceState, EventHandler anyPropertyChangedHandler)
    {
    	if (this.LocalPropertyChanged == null && this.AnyPropertyChanged == null)
    	{
    		if(resetPersistenceState) 
    		{
    			this.PersistanceState = PState.Unchanged;
    			this.Dirty = false;
    		}
    
    		this.LocalPropertyChanged += HandleLocalPropertyChanged;
            this.AnyPropertyChanged += anyPropertyChangedHandler;
    		if(Countries != null)
    		{
    			foreach(var n in Countries) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    		if(Functions != null)
    		{
    			foreach(var n in Functions) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    		if(Modules != null)
    		{
    			foreach(var n in Modules) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    		if(Status != null)
    		{
    			foreach(var n in Status) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    		if(TranslationItems != null)
    		{
    			foreach(var n in TranslationItems) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    	}
    }
    
    public override void DeactivatePropertyChangedEvent()
    {
    	if(this.LocalPropertyChanged != null && this.AnyPropertyChanged != null) 
    	{
    		this.LocalPropertyChanged = null;
    		this.AnyPropertyChanged = null;
    		foreach(var n in Countries) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in Functions) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in Modules) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in Status) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in TranslationItems) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    	}
    }
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
