//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Woozle.Model
{
    [Serializable]
    public partial class User : WoozleObject, IManagedConcurrency
    {
        public User()
        {
            this.UserMandatorRoles = new FixupCollection<UserMandatorRole>();
        }
    
        private string username;
        private string password;
        private bool flagactive;
        private Nullable<System.DateTime> lastlogin;
        private Nullable<System.DateTime> lastpasswordchange;
        private int languageid;
        private int flagactivestatusid;
        private byte[] changecounter;
        private string firstname;
        private string lastname;
    
        public string Username 
    	{ 
    		get { return this.username;} 
    		set { 
    			if(this.username != value)
    			{
    				this.username = value;
    				OnPropertyChanged("Username");
    			}
    		}
    	}
        public string Password 
    	{ 
    		get { return this.password;} 
    		set { 
    			if(this.password != value)
    			{
    				this.password = value;
    				OnPropertyChanged("Password");
    			}
    		}
    	}
        public bool FlagActive 
    	{ 
    		get { return this.flagactive;} 
    		set { 
    			if(this.flagactive != value)
    			{
    				this.flagactive = value;
    				OnPropertyChanged("FlagActive");
    			}
    		}
    	}
        public Nullable<System.DateTime> LastLogin 
    	{ 
    		get { return this.lastlogin;} 
    		set { 
    			if(this.lastlogin != value)
    			{
    				this.lastlogin = value;
    				OnPropertyChanged("LastLogin");
    			}
    		}
    	}
        public Nullable<System.DateTime> LastPasswordChange 
    	{ 
    		get { return this.lastpasswordchange;} 
    		set { 
    			if(this.lastpasswordchange != value)
    			{
    				this.lastpasswordchange = value;
    				OnPropertyChanged("LastPasswordChange");
    			}
    		}
    	}
        public int LanguageId 
    	{ 
    		get { return this.languageid;} 
    		set { 
    			if(this.languageid != value)
    			{
    				this.languageid = value;
    				OnPropertyChanged("LanguageId");
    			}
    		}
    	}
        public int FlagActiveStatusId 
    	{ 
    		get { return this.flagactivestatusid;} 
    		set { 
    			if(this.flagactivestatusid != value)
    			{
    				this.flagactivestatusid = value;
    				OnPropertyChanged("FlagActiveStatusId");
    			}
    		}
    	}
        public byte[] ChangeCounter 
    	{ 
    		get { return this.changecounter;} 
    		set { 
    			if(this.changecounter != value)
    			{
    				this.changecounter = value;
    				OnPropertyChanged("ChangeCounter");
    			}
    		}
    	}
        public string FirstName 
    	{ 
    		get { return this.firstname;} 
    		set { 
    			if(this.firstname != value)
    			{
    				this.firstname = value;
    				OnPropertyChanged("FirstName");
    			}
    		}
    	}
        public string LastName 
    	{ 
    		get { return this.lastname;} 
    		set { 
    			if(this.lastname != value)
    			{
    				this.lastname = value;
    				OnPropertyChanged("LastName");
    			}
    		}
    	}
    
    
    public virtual Language Language { get; set; }
    
    
    public virtual Status Status { get; set; }
    
    
    private FixupCollection<UserMandatorRole> usermandatorroles;
    
    public virtual FixupCollection<UserMandatorRole> UserMandatorRoles 
    { 
    	get { return usermandatorroles; } 
    	set
    	{
    		usermandatorroles = value;
    		if(value != null)
    		{
    			UserMandatorRoles.CollectionChanged += OnCollectionChanged;
    		}
    	}
    }
    
    
    public event PropertyChangedEventHandler LocalPropertyChanged;
    private event EventHandler AnyPropertyChanged;
    
    protected void OnPropertyChanged(String propertyName)
    {
    	if (this.LocalPropertyChanged != null)
        {
            this.LocalPropertyChanged(this, new PropertyChangedEventArgs(propertyName));
        }
    }
    
    private void OnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
    {
    	OnPropertyChanged("Collection");
    }
    
    public void HandleLocalPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
    	this.PersistanceState = PState.Modified;
    	AnyPropertyChanged(sender, e);
    }
    
    public void HandleAnyPropertyChanged(object sender, EventArgs e)
    {
    	this.Dirty = true;
    }
    
    public override void ActivatePropertyChangedEvent(bool resetPersistenceState)
    {
    	ActivatePropertyChangedEvent(resetPersistenceState, HandleAnyPropertyChanged);
    }
    
    public void ActivatePropertyChangedEvent(bool resetPersistenceState, EventHandler anyPropertyChangedHandler)
    {
    	if (this.LocalPropertyChanged == null && this.AnyPropertyChanged == null)
    	{
    		if(resetPersistenceState) 
    		{
    			this.PersistanceState = PState.Unchanged;
    			this.Dirty = false;
    		}
    
    		this.LocalPropertyChanged += HandleLocalPropertyChanged;
            this.AnyPropertyChanged += anyPropertyChangedHandler;
    
    		if(Language != null)
    		{
    			Language.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    		}
    
    
    		if(Status != null)
    		{
    			Status.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    		}
    
    		if(UserMandatorRoles != null)
    		{
    			foreach(var n in UserMandatorRoles) 
    			{
    				n.ActivatePropertyChangedEvent(resetPersistenceState, anyPropertyChangedHandler);
    			}
    		}
    	
    
    	}
    }
    
    public override void DeactivatePropertyChangedEvent()
    {
    	if(this.LocalPropertyChanged != null && this.AnyPropertyChanged != null) 
    	{
    		this.LocalPropertyChanged = null;
    		this.AnyPropertyChanged = null;
    		if(Language != null)
    		{
    			Language.DeactivatePropertyChangedEvent();
    		}
    		if(Status != null)
    		{
    			Status.DeactivatePropertyChangedEvent();
    		}
    		foreach(var n in UserMandatorRoles) 
    		{
    			n.DeactivatePropertyChangedEvent();
    		}
    	}
    }
    
    public override bool Equals(object obj)
    {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (GetType() != obj.GetType())
            return false;
    	//objects are equal when they are not new (Id != 0) and the Ids are equal
        WoozleObject other = (WoozleObject)obj;
        if (Id == 0 || Id != other.Id)
            return false;
        return true;
    }
    
    public override int GetHashCode()
    {
        int prime = 31;
    	int result = 1;
    	result = prime * result + Id;
    	return result;
    }
    }
    
}
