//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Woozle.Core.Services.Stack.ServiceModel.LocationManagement
{
    [Serializable]
    public partial class City : WoozleDto
    {
        public string ZipCode { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
    }
    
}
