//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using ServiceStack;
using ServiceStack.ServiceHost;

namespace Woozle.Services.Location
{
    [Serializable]
    [Route("/locations", "POST,PUT,DELETE")]
    [Route("/locations/{Id}")]
    public partial class LocationDto : WoozleDto, IReturn<LocationDto>, IReturn<SaveResult<LocationDto>>, IReturnVoid 
    {
        public string Name { get; set; }
        public string Street { get; set; }
        public Nullable<int> CityId { get; set; }
    
        public City City { get; set; }
        public Mandator.Mandator Mandator { get; set; }
    }
    
}
