//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Woozle.Core.Services.Stack.ServiceModel.Translation
{
    [Serializable]
    public partial class Message : WoozleDto
    {
        public string Code { get; set; }
        public int TranslationId { get; set; }
    
    	/// <summary>
        /// To use the translated value directly it needs to be filled explicit
        /// </summary>
        public string TranslatedValue { get; set; }

        public ServiceModel.Translation.Translation Translation { get; set; }
    
    }
    
}
