//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;
using Woozle.Core.Services.Stack.ServiceModel;

namespace Woozle.Core.Services.Stack.ServiceModel.Translation
{
    [Serializable]
    public partial class Translation : WoozleDto
    {
        public string DefaultDescription { get; set; }
    }
    
}
