//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Woozle.Services.Location
{
    [Serializable]
    public partial class TranslationItemDto : WoozleDto
    {
        public int TranslationId { get; set; }
        public int LanguageId { get; set; }
        public string Description { get; set; }
    
        public Language Language { get; set; }
        public Translation Translation { get; set; }
    
    }
    
}
