//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Woozle.Services;

namespace Woozle.Services.Fields
{
    [Serializable]
    public partial class StatusField : WoozleDto
    {
        public string Name { get; set; }
    }
}
