//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Woozle.Services.Authority
{
    [Serializable]
    public partial class MandatorRole : WoozleDto
    {
    
        public int MandId { get; set; }
        public int RoleId { get; set; }
    
        public Mandator.Mandator Mandator { get; set; }
        public Role Role { get; set; }
    
    }
    
}
